name: Bug report
description: Report errors or unexpected behavior to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting issues of Vertopal CLI.

        To make it easier for us to help you please enter detailed information below.
  - type: textarea
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is and what happens exactly.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps (or code) to reproduce
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System
      description: >
        Your operating system name, version and desktop environment.
        Also, include your Python version if you are using Vertopal CLI as a Python package.
    validations:
      required: true
  - type: input
    attributes:
      label: Version of Vertopal CLI
      description: >
        **Don't use 'latest'**, specify actual version.
        Execute `vertopal --version` command to get version number.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Installation source
      multiple: false
      options:
        - Static binary from official website
        - Automatic installer from official website
        - Static binary from GitHub release page
        - Python Package Index (PyPI)
        - Other (unofficial) source
    validations:
      required: true
