# This workflow will build and release executable binaries 
# of vertopal/vertopal.py script, using PyInstaller on different platforms.

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build & Release Binaries

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build binaries

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-20.04
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - if: matrix.os == 'windows-latest'
        name: Install Python dependencies (Compile PyInstaller Bootloader)
        env:
          PYINSTALLER_COMPILE_BOOTLOADER: 1
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install "PyInstaller==5.7.0" --no-binary "PyInstaller==5.7.0"

      - if: matrix.os != 'windows-latest'
        name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller
          pip install -r requirements.txt

      - name: Build using Vertopal build.py
        run: |
          cd vertopal
          python build.py --version ${{ github.ref_name }} --delete-bin

      - name: Deploy artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vertopal-${{ matrix.os }}
          path: vertopal/dist/vertopal*.zip
          if-no-files-found: error

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Get deployed artifacts
        uses: actions/download-artifact@v3

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: Vertopal CLI ${{ github.ref_name }}
          prerelease: false
          files: |
            vertopal-windows-latest/*
            vertopal-macos-latest/*
            vertopal-ubuntu-20.04/*
